### ISSUE TITLE
1.3.0 has invalid NPM package

### ISSUE THREAD

**Issue by codyfyi** [lbenie/reading-time-estimator#120]
I performed a fresh NPM install of reading-time-estimator @1.3.0 and typescript immediately displayed an error:

> Cannot find module 'reading-time-estimator' or its corresponding type declarations.ts(2307)

I checked the package contents and noticed it is missing the `dist` directory so these resolutions fail:

```
...
  "main": "./dist/umd/index.umd.js",
  "module": "./dist/esm/index.es6.js",
  "types": "./dist/types/lib/index.d.ts",
...
```

I changed my package.json to use reading-time-estimator @1.2.0 and it works correctly.

**Comment by lbenie** [comment]
thanks for reporting, I'll look into it

**Comment by lbenie** [comment]
Should be fixed with `1.3.2`

**Comment by codyfyi** [comment]
@lbenie - Thanks for the quick response! It looks like `main` and `module` now resolve correctly but there is still a problem with `types`:

```
"types": "./dist/types/lib/index.d.ts",
```
There is no `lib` folder in the dist path so it should just be `./dist/types/index.d.ts`.

The library is very useful - much appreciated!

**Comment by lbenie** [comment]
Will fix in a few

**Comment by lbenie** [comment]
Should be fixed now in `1.3.3`

**Comment by codyfyi** [comment]
Looks good!
